final List<Map> InterfaceCons = [
  {'id_type': '0', 'type': 'الكل'},
  {'id_type': '1', 'type': 'شمال'},
  {'id_type': '2', 'type': 'شرق'},
  {'id_type': '3', 'type': 'غرب'},
  {'id_type': '4', 'type': 'جنوب'},
  {'id_type': '5', 'type': 'شمال شرقي'},
  {'id_type': '6', 'type': 'جنوب شرقي'},
  {'id_type': '7', 'type': 'جنوب غربي'},
  {'id_type': '8', 'type': 'شمال غربي'},
  {'id_type': '9', 'type': 'جنوبي شمالي'},
  {'id_type': '10', 'type': 'شرقي غربي'},
  {'id_type': '11', 'type': '3 شوارع'},
  {'id_type': '12', 'type': '4 شوارع'},
];
final List<Map> EnInterfaceCons = [
  {'id_type': '0', 'type': 'All'},
  {'id_type': '1', 'type': 'North'},
  {'id_type': '2', 'type': 'East'},
  {'id_type': '3', 'type': 'West'},
  {'id_type': '4', 'type': 'South'},
  {'id_type': '5', 'type': 'Eastnorth'},
  {'id_type': '6', 'type': 'Eastsouth'},
  {'id_type': '7', 'type': 'Westsouth'},
  {'id_type': '8', 'type': 'Westnorth'},
  {'id_type': '9', 'type': 'South North'},
  {'id_type': '10', 'type': 'East West'},
  {'id_type': '11', 'type': '3 Roads'},
  {'id_type': '12', 'type': '4 Roads'},
];
final List<Map> StreetWidthCons = [
  {'id_type': '0', 'type': 'الكل'},
  {'id_type': '5', 'type': 'أكثر من 5'},
  {'id_type': '10', 'type': 'أكثر من 10'},
  {'id_type': '15', 'type': 'أكثر من 15'},
  {'id_type': '20', 'type': 'أكثر من 20'},
  {'id_type': '25', 'type': 'أكثر من 25'},
  {'id_type': '30', 'type': 'أكثر من 30'},
  {'id_type': '35', 'type': 'أكثر من 35'},
  {'id_type': '40', 'type': 'أكثر من 40'},
  {'id_type': '45', 'type': 'أكثر من 45'},
  {'id_type': '50', 'type': 'أكثر من 50'},
];
final List<Map> EnStreetWidthCons = [
  {'id_type': '0', 'type': 'All'},
  {'id_type': '5', 'type': 'More than 5'},
  {'id_type': '10', 'type': 'More than 10'},
  {'id_type': '15', 'type': 'More than 15'},
  {'id_type': '20', 'type': 'More than 20'},
  {'id_type': '25', 'type': 'More than 25'},
  {'id_type': '30', 'type': 'More than 30'},
  {'id_type': '35', 'type': 'More than 35'},
  {'id_type': '40', 'type': 'More than 40'},
  {'id_type': '45', 'type': 'More than 45'},
  {'id_type': '50', 'type': 'More than 50'},
];
final List<Map> AgeOfRealEstateCons = [
  {'id_type': '0', 'type': 'الكل'},
  {'id_type': '1', 'type': 'أقل من سنة'},
  {'id_type': '2', 'type': 'أقل من 2 سنة'},
  {'id_type': '3', 'type': 'أقل من 3 سنة'},
  {'id_type': '4', 'type': 'أقل من 4 سنة'},
  {'id_type': '5', 'type': 'أقل من 5 سنة'},
  {'id_type': '6', 'type': 'أقل من 6 سنة'},
  {'id_type': '7', 'type': 'أقل من 7 سنة'},
  {'id_type': '8', 'type': 'أقل من 8 سنة'},
  {'id_type': '9', 'type': 'أقل من 9 سنة'},
  {'id_type': '10', 'type': 'أقل من 10 سنة'},
  {'id_type': '11', 'type': 'أقل من 11 سنة'},
  {'id_type': '12', 'type': 'أقل من 12 سنة'},
  {'id_type': '13', 'type': 'أقل من 13 سنة'},
  {'id_type': '14', 'type': 'أقل من 14 سنة'},
  {'id_type': '15', 'type': 'أقل من 15 سنة'},
  {'id_type': '16', 'type': 'أقل من 16 سنة'},
  {'id_type': '17', 'type': 'أقل من 17 سنة'},
  {'id_type': '18', 'type': 'أقل من 18 سنة'},
  {'id_type': '19', 'type': 'أقل من 19 سنة'},
  {'id_type': '20', 'type': 'أقل من 20 سنة'},
];
final List<Map> EnAgeOfRealEstateCons = [
  {'id_type': '0', 'type': 'All'},
  {'id_type': '1', 'type': 'Less than 1 years'},
  {'id_type': '2', 'type': 'Less than 2 years'},
  {'id_type': '3', 'type': 'Less than 3 years'},
  {'id_type': '4', 'type': 'Less than 4 years'},
  {'id_type': '5', 'type': 'Less than 5 years'},
  {'id_type': '6', 'type': 'Less than 6 years'},
  {'id_type': '7', 'type': 'Less than 7 years'},
  {'id_type': '8', 'type': 'Less than 8 years'},
  {'id_type': '9', 'type': 'Less than 9 years'},
  {'id_type': '10', 'type': 'Less than 10 years'},
  {'id_type': '11', 'type': 'Less than 11 years'},
  {'id_type': '12', 'type': 'Less than 12 years'},
  {'id_type': '13', 'type': 'Less than 13 years'},
  {'id_type': '14', 'type': 'Less than 14 years'},
  {'id_type': '15', 'type': 'Less than 15 years'},
  {'id_type': '16', 'type': 'Less than 16 years'},
  {'id_type': '17', 'type': 'Less than 17 years'},
  {'id_type': '18', 'type': 'Less than 18 years'},
  {'id_type': '19', 'type': 'Less than 19 years'},
  {'id_type': '20', 'type': 'Less than 20 years'},
];
final List<Map> StoresCons = [
  {'id_type': '0', 'type': 'الكل'},
  {'id_type': '1', 'type': '1'},
  {'id_type': '2', 'type': '2'},
  {'id_type': '3', 'type': '3'},
  {'id_type': '4', 'type': '4'},
];
final List<Map> EnStoresCons = [
  {'id_type': '0', 'type': 'All'},
  {'id_type': '1', 'type': '1'},
  {'id_type': '2', 'type': '2'},
  {'id_type': '3', 'type': '3'},
  {'id_type': '4', 'type': '4'},
];
final List<Map> TreesCons = [
  {'id_type': '0', 'type': 'الكل'},
  {'id_type': '100', 'type': 'أقل من 100 أشجار'},
  {'id_type': '200', 'type': 'أقل من 200 أشجار'},
  {'id_type': '500', 'type': 'أقل من 500 أشجار'},
  {'id_type': '1000', 'type': 'أقل من 1000 أشجار'},
  {'id_type': '2000', 'type': 'أقل من 2000 أشجار'},
  {'id_type': '5000', 'type': 'أقل من 5000 أشجار'},
  {'id_type': '10000', 'type': 'أقل من 10000 أشجار'},
];
final List<Map> EnTreesCons = [
  {'id_type': '0', 'type': 'All'},
  {'id_type': '100', 'type': 'Less than 100 trees'},
  {'id_type': '200', 'type': 'Less than 200 trees'},
  {'id_type': '500', 'type': 'Less than 500 trees'},
  {'id_type': '1000', 'type': 'Less than 1000 trees'},
  {'id_type': '2000', 'type': 'Less than 2000 trees'},
  {'id_type': '5000', 'type': 'Less than 5000 trees'},
  {'id_type': '10000', 'type': 'Less than 10000 trees'},
];
final List<Map> WellsCons = [
  {'id_type': '0', 'type': 'الكل'},
  {'id_type': '1', 'type': '1'},
  {'id_type': '2', 'type': '2'},
  {'id_type': '3', 'type': '3'},
  {'id_type': '4', 'type': '4'},
  {'id_type': '5', 'type': '5'},
  {'id_type': '6', 'type': '6'},
  {'id_type': '7', 'type': '7'},
  {'id_type': '8', 'type': '8'},
  {'id_type': '9', 'type': '9'},
  {'id_type': '10', 'type': '10'},
];
final List<Map> EnWellsCons = [
  {'id_type': '0', 'type': 'All'},
  {'id_type': '1', 'type': '1'},
  {'id_type': '2', 'type': '2'},
  {'id_type': '3', 'type': '3'},
  {'id_type': '4', 'type': '4'},
  {'id_type': '5', 'type': '5'},
  {'id_type': '6', 'type': '6'},
  {'id_type': '7', 'type': '7'},
  {'id_type': '8', 'type': '8'},
  {'id_type': '9', 'type': '9'},
  {'id_type': '10', 'type': '10'},
];
final List<Map> FloorCons = [
  {'id_type': '0', 'type': 'الكل'},
  {'id_type': '1', 'type': 'دور أرضي'},
  {'id_type': '2', 'type': 'دور علوي'},
  {'id_type': '3', 'type': '3'},
  {'id_type': '4', 'type': '4'},
  {'id_type': '5', 'type': '5'},
  {'id_type': '6', 'type': '6'},
  {'id_type': '7', 'type': '7'},
  {'id_type': '8', 'type': '8'},
  {'id_type': '9', 'type': '9'},
  {'id_type': '10', 'type': '10'},
  {'id_type': '11', 'type': '11'},
  {'id_type': '12', 'type': '12'},
  {'id_type': '13', 'type': '13'},
  {'id_type': '14', 'type': '14'},
  {'id_type': '15', 'type': '15'},
];
final List<Map> EnFloorCons = [
  {'id_type': '0', 'type': 'All'},
  {'id_type': '1', 'type': 'Ground Floor'},
  {'id_type': '2', 'type': 'Upstairs'},
  {'id_type': '3', 'type': '3'},
  {'id_type': '4', 'type': '4'},
  {'id_type': '5', 'type': '5'},
  {'id_type': '6', 'type': '6'},
  {'id_type': '7', 'type': '7'},
  {'id_type': '8', 'type': '8'},
  {'id_type': '9', 'type': '9'},
  {'id_type': '10', 'type': '10'},
  {'id_type': '11', 'type': '11'},
  {'id_type': '12', 'type': '12'},
  {'id_type': '13', 'type': '13'},
  {'id_type': '14', 'type': '14'},
  {'id_type': '15', 'type': '15'},
];

List<Map> categoriesCons() {
  var _categories = <Map>[
    {'id_category': '0', 'name': 'الكل'},
    {'id_category': '1', 'name': 'فيلا للبيع'},
    {'id_category': '2', 'name': 'أرض للبيع'},
    {'id_category': '3', 'name': 'عمارة للبيع'},
    {'id_category': '4', 'name': 'بيت للبيع'},
    {'id_category': '5', 'name': 'استراحة للبيع'},
    {'id_category': '6', 'name': 'مزرعة للبيع'},
    {'id_category': '7', 'name': 'مستودع للبيع'},
    {'id_category': '8', 'name': 'شقة للبيع'},
    {'id_category': '9', 'name': 'فيلا للإيجار'},
    {'id_category': '10', 'name': 'أرض للإيجار'},
    {'id_category': '11', 'name': 'عمارة للإيجار'},
    {'id_category': '12', 'name': 'استراحة للإيجار'},
    {'id_category': '13', 'name': 'مزرعة للإيجار'},
    {'id_category': '14', 'name': 'شقة للإيجار'},
    {'id_category': '15', 'name': 'دور للإيجار'},
    {'id_category': '16', 'name': 'مكتب للإيجار'},
    {'id_category': '17', 'name': 'غرفة للإيجار'},
    {'id_category': '18', 'name': 'محل للإيجار'},
    {'id_category': '19', 'name': 'مستودع للإيجار'},
    {'id_category': '20', 'name': 'مخيم للإيجار'},
    {'id_category': '21', 'name': 'محل للتقبيل'},
  ];
  return _categories;
}
List<Map> enCategoriesCons() {
  var _enCategories = <Map>[
    {'id_category': '0', 'name': 'All'},
    {'id_category': '1', 'name': 'Villa for sale'},
    {'id_category': '2', 'name': 'Land for sale'},
    {'id_category': '3', 'name': 'Building for sale'},
    {'id_category': '4', 'name': 'House for sale'},
    {'id_category': '5', 'name': 'Chalet for sale'},
    {'id_category': '6', 'name': 'Farm for sale'},
    {'id_category': '7', 'name': 'Warehouse for sale'},
    {'id_category': '8', 'name': 'Apartment for sale'},
    {'id_category': '9', 'name': 'Villa for rent'},
    {'id_category': '10', 'name': 'Land for rent'},
    {'id_category': '11', 'name': 'Building for rent'},
    {'id_category': '12', 'name': 'Chalet for rent'},
    {'id_category': '13', 'name': 'Farm for rent'},
    {'id_category': '14', 'name': 'Apartment for rent'},
    {'id_category': '15', 'name': 'Floor for rent'},
    {'id_category': '16', 'name': 'Office for rent'},
    {'id_category': '17', 'name': 'Room for rent'},
    {'id_category': '18', 'name': 'Shop for rent'},
    {'id_category': '19', 'name': 'Warehouse for rent'},
    {'id_category': '20', 'name': 'Camp for rent'},
    {'id_category': '21', 'name': 'Shop for sale'},
  ];
  return _enCategories;
}