name: tadawl_app
description: Real-Estate Tadawl App .
publish_to: 'none'
version: 1.6.6+36
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  google_maps_flutter: ^2.0.8
  location: ^4.3.0
  http: ^0.13.3
  share: ^2.0.4
  url_launcher: ^6.0.10
  fluttertoast: ^8.0.8
  image_picker: ^0.8.4
  whatsapp_unilink: ^2.0.0
  flutter_switch: ^0.3.2
  video_player: ^2.1.15
  cached_network_image: ^3.1.0
  shared_preferences:
  animated_splash_screen: ^1.1.0
  intl: ^0.17.0
  jiffy: ^4.1.0
  flutter_image_compress: ^1.1.0
  geocoding: ^2.0.1
  flutter_phone_direct_caller: ^2.0.0
  path_provider: ^2.0.3
  pinch_zoom_image_last: ^0.4.1
  charts_flutter: ^0.11.0
  provider: ^5.0.0
  rating_dialog: ^2.0.0
  google_fonts: ^2.1.0
  dcache: ^0.4.0
  flutter_local_notifications: ^8.1.1+2
  file_picker: ^4.0.1
  chewie: ^1.2.2
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.2.1
  qr_flutter: ^4.0.0
  record: ^3.0.0
  just_audio: ^0.9.9
  permission_handler: ^8.1.4+2
  pdf: ^3.6.0
  flutter_simple_rating_bar:
    git:
      url: https://github.com/docwei2050/flutter_simple_rating_bar.git

  # flutter_video_compress:
  # This packages added
  # flutter_automation:
  #  page_transition: ^2.0.1-nullsafety.0
  #  search_map_place:
  #  get_it: ^7.2.0
  #  geolocator: ^7.6.0
  #  number_display: ^3.0.0
  #  wechat_assets_picker: ^6.0.4
  #  flutter_absolute_path: # No null safety
  #  timeago: ^3.1.0
  #  image: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  build_runner: ^2.1.2
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: DINNext
      fonts:
        - asset: assets/DINNext-Regular.ttf
        - asset: assets/DINNext-UltraLight.ttf